// protoc --go_out=deploy-manager/pkg/proto --go-grpc_out=deploy-manager/pkg/proto deploy-manager/pkg/proto/deploy.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: deploy-manager/pkg/proto/deploy.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filepath string `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_deploy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_deploy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

type DeployReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`
}

func (x *DeployReply) Reset() {
	*x = DeployReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_deploy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReply) ProtoMessage() {}

func (x *DeployReply) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_deploy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployReply.ProtoReflect.Descriptor instead.
func (*DeployReply) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *DeployReply) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

var File_deploy_manager_pkg_proto_deploy_proto protoreflect.FileDescriptor

var file_deploy_manager_pkg_proto_deploy_proto_rawDesc = []byte{
	0x0a, 0x25, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b,
	0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0x27, 0x0a, 0x0b, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x32, 0x3e, 0x0a, 0x06, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x34,
	0x0a, 0x06, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_deploy_manager_pkg_proto_deploy_proto_rawDescOnce sync.Once
	file_deploy_manager_pkg_proto_deploy_proto_rawDescData = file_deploy_manager_pkg_proto_deploy_proto_rawDesc
)

func file_deploy_manager_pkg_proto_deploy_proto_rawDescGZIP() []byte {
	file_deploy_manager_pkg_proto_deploy_proto_rawDescOnce.Do(func() {
		file_deploy_manager_pkg_proto_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(file_deploy_manager_pkg_proto_deploy_proto_rawDescData)
	})
	return file_deploy_manager_pkg_proto_deploy_proto_rawDescData
}

var file_deploy_manager_pkg_proto_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deploy_manager_pkg_proto_deploy_proto_goTypes = []any{
	(*DeployRequest)(nil), // 0: proto.DeployRequest
	(*DeployReply)(nil),   // 1: proto.DeployReply
}
var file_deploy_manager_pkg_proto_deploy_proto_depIdxs = []int32{
	0, // 0: proto.Deploy.Deploy:input_type -> proto.DeployRequest
	1, // 1: proto.Deploy.Deploy:output_type -> proto.DeployReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deploy_manager_pkg_proto_deploy_proto_init() }
func file_deploy_manager_pkg_proto_deploy_proto_init() {
	if File_deploy_manager_pkg_proto_deploy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deploy_manager_pkg_proto_deploy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeployRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_deploy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DeployReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deploy_manager_pkg_proto_deploy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deploy_manager_pkg_proto_deploy_proto_goTypes,
		DependencyIndexes: file_deploy_manager_pkg_proto_deploy_proto_depIdxs,
		MessageInfos:      file_deploy_manager_pkg_proto_deploy_proto_msgTypes,
	}.Build()
	File_deploy_manager_pkg_proto_deploy_proto = out.File
	file_deploy_manager_pkg_proto_deploy_proto_rawDesc = nil
	file_deploy_manager_pkg_proto_deploy_proto_goTypes = nil
	file_deploy_manager_pkg_proto_deploy_proto_depIdxs = nil
}
