// protoc --go_out=rbac-manager/pkg/proto --go-grpc_out=rbac-manager/pkg/proto rbac-manager/pkg/proto/rbac.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: deploy-manager/pkg/proto/manifest.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group   string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind    string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   string    `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Annotations []string  `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Label       []*Labels `protobuf:"bytes,4,rep,name=label,proto3" json:"label,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetLabel() []*Labels {
	if x != nil {
		return x.Label
	}
	return nil
}

type Labels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Labels) Reset() {
	*x = Labels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *Labels) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Labels) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Value string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *Spec) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Spec) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SuccessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`
}

func (x *SuccessReply) Reset() {
	*x = SuccessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessReply) ProtoMessage() {}

func (x *SuccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessReply.ProtoReflect.Descriptor instead.
func (*SuccessReply) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *SuccessReply) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type ApplyManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group       *Manifest   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version     *Manifest   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind        *Manifest   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name        *Metadata   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   *Metadata   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Annotations []*Metadata `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty"`
	Label       []*Metadata `protobuf:"bytes,7,rep,name=label,proto3" json:"label,omitempty"`
}

func (x *ApplyManifestRequest) Reset() {
	*x = ApplyManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyManifestRequest) ProtoMessage() {}

func (x *ApplyManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyManifestRequest.ProtoReflect.Descriptor instead.
func (*ApplyManifestRequest) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyManifestRequest) GetGroup() *Manifest {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *ApplyManifestRequest) GetVersion() *Manifest {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ApplyManifestRequest) GetKind() *Manifest {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ApplyManifestRequest) GetName() *Metadata {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ApplyManifestRequest) GetNamespace() *Metadata {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ApplyManifestRequest) GetAnnotations() []*Metadata {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ApplyManifestRequest) GetLabel() []*Metadata {
	if x != nil {
		return x.Label
	}
	return nil
}

type DeleteManifestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group     *Manifest `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version   *Manifest `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind      *Manifest `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name      *Metadata `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace *Metadata `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *DeleteManifestRequest) Reset() {
	*x = DeleteManifestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestRequest) ProtoMessage() {}

func (x *DeleteManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_manager_pkg_proto_manifest_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestRequest.ProtoReflect.Descriptor instead.
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteManifestRequest) GetGroup() *Manifest {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *DeleteManifestRequest) GetVersion() *Manifest {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DeleteManifestRequest) GetKind() *Manifest {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *DeleteManifestRequest) GetName() *Metadata {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *DeleteManifestRequest) GetNamespace() *Metadata {
	if x != nil {
		return x.Namespace
	}
	return nil
}

var File_deploy_manager_pkg_proto_manifest_proto protoreflect.FileDescriptor

var file_deploy_manager_pkg_proto_manifest_proto_rawDesc = []byte{
	0x0a, 0x27, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6e, 0x69, 0x66,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4e, 0x0a, 0x08, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x22, 0x83, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x23, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x30, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x22, 0xbb, 0x02, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61,
	0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0b,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x22, 0xe2, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x32, 0x9d, 0x01, 0x0a, 0x0f, 0x4d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deploy_manager_pkg_proto_manifest_proto_rawDescOnce sync.Once
	file_deploy_manager_pkg_proto_manifest_proto_rawDescData = file_deploy_manager_pkg_proto_manifest_proto_rawDesc
)

func file_deploy_manager_pkg_proto_manifest_proto_rawDescGZIP() []byte {
	file_deploy_manager_pkg_proto_manifest_proto_rawDescOnce.Do(func() {
		file_deploy_manager_pkg_proto_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(file_deploy_manager_pkg_proto_manifest_proto_rawDescData)
	})
	return file_deploy_manager_pkg_proto_manifest_proto_rawDescData
}

var file_deploy_manager_pkg_proto_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_deploy_manager_pkg_proto_manifest_proto_goTypes = []any{
	(*Manifest)(nil),              // 0: proto.Manifest
	(*Metadata)(nil),              // 1: proto.Metadata
	(*Labels)(nil),                // 2: proto.Labels
	(*Spec)(nil),                  // 3: proto.Spec
	(*SuccessReply)(nil),          // 4: proto.SuccessReply
	(*ApplyManifestRequest)(nil),  // 5: proto.ApplyManifestRequest
	(*DeleteManifestRequest)(nil), // 6: proto.DeleteManifestRequest
}
var file_deploy_manager_pkg_proto_manifest_proto_depIdxs = []int32{
	2,  // 0: proto.Metadata.label:type_name -> proto.Labels
	0,  // 1: proto.ApplyManifestRequest.group:type_name -> proto.Manifest
	0,  // 2: proto.ApplyManifestRequest.version:type_name -> proto.Manifest
	0,  // 3: proto.ApplyManifestRequest.kind:type_name -> proto.Manifest
	1,  // 4: proto.ApplyManifestRequest.name:type_name -> proto.Metadata
	1,  // 5: proto.ApplyManifestRequest.namespace:type_name -> proto.Metadata
	1,  // 6: proto.ApplyManifestRequest.annotations:type_name -> proto.Metadata
	1,  // 7: proto.ApplyManifestRequest.label:type_name -> proto.Metadata
	0,  // 8: proto.DeleteManifestRequest.group:type_name -> proto.Manifest
	0,  // 9: proto.DeleteManifestRequest.version:type_name -> proto.Manifest
	0,  // 10: proto.DeleteManifestRequest.kind:type_name -> proto.Manifest
	1,  // 11: proto.DeleteManifestRequest.name:type_name -> proto.Metadata
	1,  // 12: proto.DeleteManifestRequest.namespace:type_name -> proto.Metadata
	5,  // 13: proto.ManifestService.ApplyManifest:input_type -> proto.ApplyManifestRequest
	6,  // 14: proto.ManifestService.DeleteManifest:input_type -> proto.DeleteManifestRequest
	4,  // 15: proto.ManifestService.ApplyManifest:output_type -> proto.SuccessReply
	4,  // 16: proto.ManifestService.DeleteManifest:output_type -> proto.SuccessReply
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_deploy_manager_pkg_proto_manifest_proto_init() }
func file_deploy_manager_pkg_proto_manifest_proto_init() {
	if File_deploy_manager_pkg_proto_manifest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Manifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Labels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SuccessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deploy_manager_pkg_proto_manifest_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteManifestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deploy_manager_pkg_proto_manifest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deploy_manager_pkg_proto_manifest_proto_goTypes,
		DependencyIndexes: file_deploy_manager_pkg_proto_manifest_proto_depIdxs,
		MessageInfos:      file_deploy_manager_pkg_proto_manifest_proto_msgTypes,
	}.Build()
	File_deploy_manager_pkg_proto_manifest_proto = out.File
	file_deploy_manager_pkg_proto_manifest_proto_rawDesc = nil
	file_deploy_manager_pkg_proto_manifest_proto_goTypes = nil
	file_deploy_manager_pkg_proto_manifest_proto_depIdxs = nil
}
