# for test
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: test-postgres
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: tester1234
      POSTGRES_DB: idp
    ports:
      - "5432:5432"

      