FROM achoistic98/base:1.22.5

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY ./.idpctl ./.idpctl

COPY ./pkg ./pkg

COPY ./deploy-manager ./deploy-manager

RUN go build -o ./dm ./deploy-manager/cmd/main.go

CMD [ "./dm", "server", "start", "-f", "/app/.idpctl/config.yaml" ]