apiVersion: v2
name: home-idp
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: keycloak
  condition: keycloak.enabled
- name: postgresql
  condition: postgresql.enabled