global:
  namespace: test-ns
  storageClass:
    name: test-sc
    size: 10Gi

secret-manager:
  enabled: true
  replicas: 3
  service:
    port: 5103
  storage:
    type: postgresql
    host: localhost
    username: tester
    password: tester1234
    database: idp
    port: 5432

deploy-manager:
  enabled: true
  replicas: 3
  service:
    port: 5104
  docker:
    host: localhost
    username: tester
    password: tester1234
    
  
rbac-manager:
  enabled: true
  replicas: 3
  service:
    port: 5105
  storage:
    type: postgresql
    host: localhost
    username: tester
    password: tester1234
    database: idp
    port: 5432
  admin:
    username: choigonyok
    password: tester1234
    email: test@naver.com
  smtp:
    enabled: true
    config:
      host: "127.0.0.1"
      port: 1587
      user: idp@choigonyok.com
      password: tester1234

gateway:
  enabled: true
  replicas: 3
  service:
    port: 5106
    type: ClusterIP
  
install-manager:
  enabled: true
  replicas: 3
  service:
    port: 5051
  docker:
    host: localhost
  defaultRegistry:
    enabled: true
    type: harbor # available values: harbor, docker-registry
    adminPassword: tester1234 # username is 'admin'
  defaultCD:
    enabled: true
    type: argocd # available values: argocd
    adminPassword: tester1234 # username is 'admin'