secret-manager:
  enabled: true
  replicas: 3
  service:
    port: 5103
  storage:
    type: postgresql
    host: "localhost"
    username: tester
    password: tester1234
    database: secretmanager
    port: 5432

    