// protoc --go_out=trace-manager/pkg/proto --go-grpc_out=trace-manager/pkg/proto trace-manager/pkg/proto/trace.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: trace-manager/pkg/proto/trace.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId     string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId      string `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ElapsedTime string `protobuf:"bytes,3,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	Status      string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message     string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Span) Reset() {
	*x = Span{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_trace_manager_pkg_proto_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetElapsedTime() string {
	if x != nil {
		return x.ElapsedTime
	}
	return ""
}

func (x *Span) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Span) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PostSpanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Span *Span `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
}

func (x *PostSpanRequest) Reset() {
	*x = PostSpanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostSpanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSpanRequest) ProtoMessage() {}

func (x *PostSpanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSpanRequest.ProtoReflect.Descriptor instead.
func (*PostSpanRequest) Descriptor() ([]byte, []int) {
	return file_trace_manager_pkg_proto_trace_proto_rawDescGZIP(), []int{1}
}

func (x *PostSpanRequest) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

type PutSpanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Span *Span `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
}

func (x *PutSpanRequest) Reset() {
	*x = PutSpanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutSpanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSpanRequest) ProtoMessage() {}

func (x *PutSpanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSpanRequest.ProtoReflect.Descriptor instead.
func (*PutSpanRequest) Descriptor() ([]byte, []int) {
	return file_trace_manager_pkg_proto_trace_proto_rawDescGZIP(), []int{2}
}

func (x *PutSpanRequest) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

type GetTracesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spans []*Span `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
}

func (x *GetTracesReply) Reset() {
	*x = GetTracesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTracesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTracesReply) ProtoMessage() {}

func (x *GetTracesReply) ProtoReflect() protoreflect.Message {
	mi := &file_trace_manager_pkg_proto_trace_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTracesReply.ProtoReflect.Descriptor instead.
func (*GetTracesReply) Descriptor() ([]byte, []int) {
	return file_trace_manager_pkg_proto_trace_proto_rawDescGZIP(), []int{3}
}

func (x *GetTracesReply) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_trace_manager_pkg_proto_trace_proto protoreflect.FileDescriptor

var file_trace_manager_pkg_proto_trace_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x04, 0x53, 0x70,
	0x61, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x70, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6c,
	0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x0f, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x22,
	0x31, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x04, 0x73, 0x70,
	0x61, 0x6e, 0x22, 0x33, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x61, 0x6e,
	0x52, 0x05, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x32, 0xc6, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74,
	0x53, 0x70, 0x61, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x53, 0x70, 0x61,
	0x6e, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x70, 0x61,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trace_manager_pkg_proto_trace_proto_rawDescOnce sync.Once
	file_trace_manager_pkg_proto_trace_proto_rawDescData = file_trace_manager_pkg_proto_trace_proto_rawDesc
)

func file_trace_manager_pkg_proto_trace_proto_rawDescGZIP() []byte {
	file_trace_manager_pkg_proto_trace_proto_rawDescOnce.Do(func() {
		file_trace_manager_pkg_proto_trace_proto_rawDescData = protoimpl.X.CompressGZIP(file_trace_manager_pkg_proto_trace_proto_rawDescData)
	})
	return file_trace_manager_pkg_proto_trace_proto_rawDescData
}

var file_trace_manager_pkg_proto_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trace_manager_pkg_proto_trace_proto_goTypes = []any{
	(*Span)(nil),            // 0: proto.Span
	(*PostSpanRequest)(nil), // 1: proto.PostSpanRequest
	(*PutSpanRequest)(nil),  // 2: proto.PutSpanRequest
	(*GetTracesReply)(nil),  // 3: proto.GetTracesReply
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_trace_manager_pkg_proto_trace_proto_depIdxs = []int32{
	0, // 0: proto.PostSpanRequest.span:type_name -> proto.Span
	0, // 1: proto.PutSpanRequest.span:type_name -> proto.Span
	0, // 2: proto.GetTracesReply.spans:type_name -> proto.Span
	1, // 3: proto.TraceService.PostSpan:input_type -> proto.PostSpanRequest
	2, // 4: proto.TraceService.PutSpan:input_type -> proto.PutSpanRequest
	4, // 5: proto.TraceService.GetTraces:input_type -> google.protobuf.Empty
	4, // 6: proto.TraceService.PostSpan:output_type -> google.protobuf.Empty
	4, // 7: proto.TraceService.PutSpan:output_type -> google.protobuf.Empty
	3, // 8: proto.TraceService.GetTraces:output_type -> proto.GetTracesReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_trace_manager_pkg_proto_trace_proto_init() }
func file_trace_manager_pkg_proto_trace_proto_init() {
	if File_trace_manager_pkg_proto_trace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trace_manager_pkg_proto_trace_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Span); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trace_manager_pkg_proto_trace_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PostSpanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trace_manager_pkg_proto_trace_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PutSpanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trace_manager_pkg_proto_trace_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetTracesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trace_manager_pkg_proto_trace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trace_manager_pkg_proto_trace_proto_goTypes,
		DependencyIndexes: file_trace_manager_pkg_proto_trace_proto_depIdxs,
		MessageInfos:      file_trace_manager_pkg_proto_trace_proto_msgTypes,
	}.Build()
	File_trace_manager_pkg_proto_trace_proto = out.File
	file_trace_manager_pkg_proto_trace_proto_rawDesc = nil
	file_trace_manager_pkg_proto_trace_proto_goTypes = nil
	file_trace_manager_pkg_proto_trace_proto_depIdxs = nil
}
