// protoc --go_out=trace-manager/pkg/proto --go-grpc_out=trace-manager/pkg/proto trace-manager/pkg/proto/trace.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: trace-manager/pkg/proto/trace.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_trace_manager_pkg_proto_trace_proto protoreflect.FileDescriptor

var file_trace_manager_pkg_proto_trace_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x0e, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_trace_manager_pkg_proto_trace_proto_goTypes = []any{}
var file_trace_manager_pkg_proto_trace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trace_manager_pkg_proto_trace_proto_init() }
func file_trace_manager_pkg_proto_trace_proto_init() {
	if File_trace_manager_pkg_proto_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trace_manager_pkg_proto_trace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trace_manager_pkg_proto_trace_proto_goTypes,
		DependencyIndexes: file_trace_manager_pkg_proto_trace_proto_depIdxs,
	}.Build()
	File_trace_manager_pkg_proto_trace_proto = out.File
	file_trace_manager_pkg_proto_trace_proto_rawDesc = nil
	file_trace_manager_pkg_proto_trace_proto_goTypes = nil
	file_trace_manager_pkg_proto_trace_proto_depIdxs = nil
}
