apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  password: {{ randAlphaNum 20 | b64enc }}
  postgres-db: a2V5Y2xvYWtfZGIK # keycloak_db
  postgres-username: aWRwYWRtaW4K # idpadmin