FROM --platform=amd64 achoistic98/base:1.22.5

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY ./.idpctl ./.idpctl

COPY ./pkg ./pkg

COPY ./rbac-manager ./rbac-manager
COPY ./trace-manager/pkg/proto ./trace-manager/pkg/proto

RUN go build -o ./rm ./rbac-manager/cmd/main.go

CMD [ "./rm", "server", "start", "-f", "/app/.idpctl/config.yaml" ]