FROM --platform=amd64 ubuntu:noble

RUN apt update

RUN apt install wget -y

RUN wget https://golang.org/dl/go1.22.5.linux-amd64.tar.gz

RUN rm -rf /usr/local/go

RUN tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin