apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-idp
subjects:
- kind: ServiceAccount
  name: home-idp-install-manager
  namespace: idp-system
- kind: ServiceAccount
  name: home-idp-deploy-manager
  namespace: idp-system
roleRef:
  kind: ClusterRole
  name: home-idp
  apiGroup: rbac.authorization.k8s.io