apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  keycloak-password: {{ randAlphaNum 20 | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }} # postgres password
  postgres-db: a2V5Y2xvYWtfZGIK # keycloak_db
  postgres-username: aWRwYWRtaW4K # idpadmin