apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-idp-install-manager
  namespace: idp-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-idp-deploy-manager
  namespace: idp-system



# apiVersion: v1
# kind: Pod
# metadata:
#   name: install-manager
#   namespace: idp-system
# spec:
#   containers:
#   - name: home-idp-install-manager
#     image: achoistic98/install-manager:latest
#     ports:
#     - containerPort: 5051
#   serviceAccountName: home-idp-install-manager
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: home-idp-deploy-manager
#   namespace: idp-system
# spec:
#   containers:
#   - name: deploy-manager
#     image: achoistic98/deploy-manager:latest
#     ports:
#     - containerPort: 5104
#   serviceAccountName: home-idp-deploy-manager